apiVersion: batch/v1
kind: Job
metadata:
  name: bmical-job
spec:
  template:
    spec:
      containers:
      - name: bmical-job
        image: yash5090/bmical:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
